import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./container/Navbar";
import "./globals.css";
import { headers } from "next/headers";
import Image from "next/image";
import Providers from "./provider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  const userAgent = headersList.get("user-agent") || "";

  const isMobile = /mobile|android|iphone|ipad|tablet/i.test(userAgent);
  return (
    <html lang="en">
      <body>
        {!isMobile ? (
          <div className="min-h-screen flex flex-col items-center justify-center bg-linear-to-br from-zinc-100 via-amber-50 to-amber-100">
            <Image
              src="/images/under-construction.gif"
              alt="Cat Rescue Logo"
              width={500}
              height={500}
              className="mix-blend-darken"
            />
            <div className="text-center space-y-4">
              <h1 className="text-4xl font-bold text-amber-800">
                🐾 Desktop Version Under Construction
              </h1>
              <p className="text-zinc-700 max-w-md mx-auto text-2xl">
                Our rescue experience is currently optimized for mobile and
                tablet devices. Please visit us using your phone.
              </p>
            </div>
          </div>
        ) : (
           <Providers>
          <div className={`${inter.className} font-sans`}>
            <Navbar />
           {children}
          </div>
          </Providers>
        )}
      </body>
    </html>
  );
}
